### ISSUE TITLE
Manual checkpoint not possible with multiple shards

### ISSUE THREAD

**Issue by Sytten** [patrobinson/gokini#5]
Hi!
I tried using the lib for consuming multiple shards and I need to manually set the checkpoint if the handling did not fail. The problem is that there is no way to know which shard is associated with the record in the `ProcessRecords` function. So you can't update the right shard for the the record.
Thanks

**Comment by patrobinson** [comment]
hey @Sytten thanks for reaching out

The `RecordConsumer` interface, which implements the `ProcessRecords` function, also has to have an `Init` method. That init method receives the shard ID as it's only argument. [See the example implementation](https://godoc.org/github.com/patrobinson/gokini#example-RecordConsumer)

Does that answer your question?

**Comment by Sytten** [comment]
Yes, but if your consumer consumes multiple shards you only get one shard id and you always update the sequence number on this shard in dynamodb  even if you consume from another shard... This leads to problems and 400 from amazon.

**Comment by patrobinson** [comment]
Right I understand now. Sorry I've got a head cold at the moment so it's hard for me to think about how we may fix this. I'll come back to this when I feel better.

**Comment by patrobinson** [comment]
@Sytten I've created a fix for this. Let me know if it suits for your use case.

**Comment by Sytten** [comment]
We didn't have to wait for the fix so we switched to the vmware version of your lib (working great in prod right now), but yeah it should be just fine.
